import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'app_settings.dart';
import 'theme/app_theme.dart';
import 'l10n/app_localizations.dart';
import 'screens/splash_screen.dart';
import 'screens/maintenance_screen.dart';
import 'api_service.dart';
import 'services/notification_service.dart';

import 'package:shared_preferences/shared_preferences.dart';

/// Background FCM handler must be top-level (wired in notification_service.dart)
/// firebase_options.dart is generated by flutterfire configure — see setup steps.
//import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print("MAIN FILE IS RUNNINGGGGG");

  // ── Firebase init ─────────────────────────────────────────────────────────
  // After running `flutterfire configure`, uncomment the line below:
  // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  //
  // For now, wrap in try/catch so the app works without Firebase configured:
  // try {
  //   await Firebase.initializeApp();
  //   await NotificationService().initialize();
  // } catch (_) {
  //   // Firebase not configured yet — app works normally, push notifications disabled
  // }
  try {
    await Firebase.initializeApp();

    await NotificationService().initialize();

    final prefs = await SharedPreferences.getInstance();
    final userId = prefs.getString('userId') ?? '';

    print("MAIN SAVED USER ID = $userId");

    if (userId.isNotEmpty) {
      await NotificationService().saveTokenForUser(userId);
    }
  } catch (e) {
    print("FIREBASE INIT ERROR = $e");
  }
  // ── App settings ──────────────────────────────────────────────────────────
  final settings = AppSettingsNotifier();
  await settings.load();

  // ── Fetch public settings (maintenance mode check) ────────────────────────
  Map<String, dynamic> publicSettings = {};
  try {
    publicSettings = await ApiService.getPublicSettings();
  } catch (_) {}

  runApp(MyApp(settings: settings, publicSettings: publicSettings));
}

class MyApp extends StatelessWidget {
  final AppSettingsNotifier settings;
  final Map<String, dynamic> publicSettings;

  const MyApp(
      {super.key, required this.settings, required this.publicSettings});

  @override
  Widget build(BuildContext context) {
    return ListenableBuilder(
      listenable: settings,
      builder: (_, __) => AppSettings(
        notifier: settings,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          navigatorKey: notificationNavigatorKey,
          theme: AppTheme.light,
          darkTheme: AppTheme.dark,
          themeMode: settings.themeMode,
          locale: settings.locale,
          supportedLocales: AppLocalizations.supportedLocales,
          localizationsDelegates: AppLocalizations.localizationsDelegates,
          home: _resolveHome(),
        ),
      ),
    );
  }

  Widget _resolveHome() {
    // If maintenance mode is on, show the maintenance screen.
    // Admins bypass this — they get to SplashScreen which routes to AdminDashboard.
    if (publicSettings['maintenanceMode'] == true) {
      return MaintenanceScreen(
        message: publicSettings['maintenanceMessage'] ?? '',
        contactEmail: publicSettings['contactEmail'] ?? '',
        contactPhone: publicSettings['contactPhone'] ?? '',
      );
    }
    return const SplashScreen();
  }
}
